services:
    Markup\NeedleBundle\Builder\SolariumSelectQueryBuilder:
        arguments:
            - '%markup_needle.debug%'

    markup_needle.solarium.plugin.log_bad_requests:
        class: Markup\NeedleBundle\EventListener\SolariumLogBadRequestsPlugin
        calls:
            - [ setLogger, [ '@logger' ] ]
            - [ setEnabled, [ '%markup_needle.solr.log_bad_requests_plugin.enabled%' ] ]
