version: 2.1

commands:
  composer:
    description: 'Configure & Install vendor packages'
    steps:
      - restore_cache:
          key: composer
      - run: composer self-update
      - run: 'curl -H "Authorization: token $COMPOSER_TOKEN" https://api.github.com/rate_limit'
      - run: composer config --global github-oauth.github.com $COMPOSER_TOKEN
      - run: composer install --no-interaction --no-progress
      - save_cache:
          key: composer
          paths:
            - ~/.composer/
  checks:
    description: 'Run checks'
    steps:
      - run: make all

jobs:
  checks:
    docker:
      - image: markupglasgow/php:7.1-cli-composer
    steps:
      - checkout
      - composer
      - checks

workflows:
  version: 2
  checks:
    jobs:
      - checks:
          filters:
            tags:
              # ensures the CI runs for tags, see https://discuss.circleci.com/t/builds-for-tags-not-triggering/17681/2
              only: /.*/
