<?php

namespace Markup\NeedleBundle\DependencyInjection;

use Markup\NeedleBundle\Terms\NullTermsFieldProvider;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('markup_needle');

        $rootNode
            ->fixXmlConfig('corpus', 'corpora')
            ->addDefaultsIfNotSet()
            ->children()
                ->arrayNode('corpora')
                    ->useAttributeAsKey('name')
                        ->prototype('array')
                        ->children()
                            ->arrayNode('schedule_index_on_events')
                                ->prototype('scalar')
                                ->end()
                            ->end()
                            ->arrayNode('backend')
                                ->addDefaultsIfNotSet()
                                ->children()
                                    ->scalarNode('type')
                                        ->isRequired()
                                        ->cannotBeEmpty()
                                        ->validate()
                                            ->ifNotInArray(['solr', 'solarium', 'elasticsearch'])
                                            ->thenInvalid('Unknown backend type "%s"')
                                        ->end()
                                    ->end()
                                    ->scalarNode('client')
                                        ->isRequired()
                                        ->cannotBeEmpty()
                                    ->end()
                                ->end()
                            ->end()
                            ->booleanNode('allow_null_values_in_update_fields')
                                ->defaultFalse()
                            ->end()
                            ->scalarNode('suggest_handler')
                                ->defaultValue('markup_needle.handler_provider.null')
                            ->end()
                            ->scalarNode('terms_service')
                                ->defaultValue('noop')
                            ->end()
                            ->scalarNode('terms_field_provider')
                                ->defaultValue(NullTermsFieldProvider::class)
                            ->end()
                            ->booleanNode('use_wildcard_search')
                                ->info('Whether to perform a wildcard search against the corpus (can be heavy)')
                                ->defaultFalse()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->booleanNode('debug')
                    ->defaultValue(false)
                ->end()
                ->booleanNode('log_bad_requests')
                    ->defaultFalse()
                ->end()
                ->arrayNode('context_services')
                    ->useAttributeAsKey('name')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('filter_provider')
                                ->defaultValue('markup_needle.filter_provider.simple')
                            ->end()
                            ->scalarNode('facet_provider')
                                ->defaultValue('markup_needle.facet_provider.simple')
                            ->end()
                            ->scalarNode('facet_set_decorator_provider')
                                ->defaultValue('markup_needle.facet_set_decorator_provider')
                            ->end()
                            ->scalarNode('facet_collator_provider')
                                ->defaultValue('markup_needle.collator_provider.null')
                            ->end()
                            ->scalarNode('facet_order_provider')
                                ->defaultValue('markup_needle.sort_order_provider.simple')
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('intercepts')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('default_domain')
                            ->defaultValue('default')
                        ->end()
                        ->arrayNode('domains')
                        ->end()
                        ->arrayNode('definitions')
                            ->useAttributeAsKey('name')
                            ->prototype('array')
                                ->fixXmlConfig('filter')
                                ->children()
                                    ->scalarNode('type')->isRequired()->cannotBeEmpty()->end()
                                    ->arrayNode('terms')
                                        ->cannotBeEmpty()
                                        ->prototype('scalar')->end()
                                    ->end()
                                    ->scalarNode('domain')->cannotBeEmpty()->end()
                                    ->scalarNode('corpus')->cannotBeEmpty()->end()
                                    ->arrayNode('filters')
                                        ->useAttributeAsKey('attr')
                                        ->prototype('variable')->end()
                                    ->end()
                                    ->scalarNode('query')->end()
                                    ->scalarNode('route')->cannotBeEmpty()->end()
                                    ->arrayNode('route_params')
                                        ->useAttributeAsKey('param')
                                        ->prototype('scalar')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
